// Here, we have 24 characters and every 2 characters
// represents a byte.

// 12 bytes
// First 4 bytes - timestamp
// Next 3 bytes - machine identifier
// Next 2 bytes - process identifier
// Last 3 bytes - counter

// In MongoDB, this ID that we have here is not generated
// by MongoDB itself. It's actually generated by MongoDB
// driver.
// Driver talks to MongoDB
// _id: 62da5b79b9a8bb0354019fa4

// Explicitly generate an object id...
const mongoose = require("mongoose");

const id = new mongoose.Types.ObjectId();
console.log(id);
console.log(id.getTimestamp());
